# Generated by Django 5.0.7 on 2024-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
