# Generated by Django 5.0.7 on 2024-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_supplier_stock_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
