# Generated by Django 5.0.7 on 2024-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_photo_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product_images/%Y/%m/'),
        ),
    ]
